Word.create([
  { draw: 'hunter' },
  { draw: 'twig' },
  { draw: 'family' },
  { draw: 'soup' },
  { draw: 'ski lift' },
  { draw: 'sneeze' },
  { draw: 'Jedi' },
  { draw: 'elf' },
  { draw: 'country' },
  { draw: 'exercise' },
  { draw: 'infection' },
  { draw: 'soulmate' },
  { draw: 'chord' },
  { draw: 'stapler' },
  { draw: 'jar' },
  { draw: 'flute' },
  { draw: 'doormat' },
  { draw: 'chalk' },
  { draw: 'bagel' },
  { draw: 'earache' },
  { draw: 'time machine' },
  { draw: 'partner' },
  { draw: 'lecture' },
  { draw: 'seat' },
  { draw: 'camera' },
  { draw: 'mouse' },
  { draw: 'monkey' },
  { draw: 'ghost' },
  { draw: 'butterfly' },
  { draw: 'jacket' },
  { draw: 'stairs' },
  { draw: 'box' },
  { draw: 'celery' },
  { draw: 'telephone' },
  { draw: 'paw' },
  { draw: 'organ' },
  { draw: 'coworker' },
  { draw: 'drip' },
  { draw: 'cartoon' },
  { draw: 'yardstick' },
  { draw: 'blush' },
  { draw: 'front' },
  { draw: 'shampoo' },
  { draw: 'goalkeeper' },
  { draw: 'hut' },
  { draw: 'chariot racing' },
  { draw: 'videogame' },
  { draw: 'taxidermist' },
  { draw: 'sheep dog' },
  { draw: 'dawn' },
  { draw: 'yacht' },
  { draw: 'cousin' },
  { draw: 'crime' },
  { draw: 'dodgeball' },
  { draw: 'grocery store' },
  { draw: 'fizz' },
  { draw: 'captain' },
  { draw: 'degree' },
  { draw: 'acrobat' },
  { draw: 'devious' },
  { draw: 'mime' },
  { draw: 'hermit crab' },
  { draw: 'rudder' },
  { draw: 'ornament' },
  { draw: 'costume' },
  { draw: 'tiptoe' },
  { draw: 'diagonal' },
  { draw: 'extension cord' },
  { draw: 'welder' },
  { draw: 'sickle' },
  { draw: 'psychologist' },
  { draw: 'one-way street' },
  { draw: 'panic' },
  { draw: 'temper' },
  { draw: 'language' },
  { draw: 'pelt' },
  { draw: 'scatter' },
  { draw: 'credit' },
  { draw: 'error' },
  { draw: 'pawnshop' },
  { draw: 'riddle' },
  { draw: 'cartoonist' },
  { draw: 'disgust' },
  { draw: 'joke' },
  { draw: 'broom' },
  { draw: 'nose' },
  { draw: 'cow' },
  { draw: 'Bart Simpson' },
  { draw: 'Homer Simpson' },
  { draw: 'Marge Simpson' },
  { draw: 'Lisa Simpson' },
  { draw: 'Maggie Simpson' },
  { draw: 'Frodo' },
  { draw: 'Gandalf' },
  { draw: 'Darth Vader' },
  { draw: 'Luke Skywalker' },
  { draw: 'Darth Maul' },
  { draw: 'Obi Wan Kenobi' },
  { draw: 'Princess Leia' },
  { draw: 'Han Solo' },
  { draw: 'Chewbaca' },
  { draw: 'Iron Man' },
  { draw: 'Spider-man' },
  { draw: 'Batman' },
  { draw: 'Superman' },
  { draw: 'Black Panther' },
  { draw: 'Green Lantern' },
  { draw: 'The Flash' },
  { draw: 'Wonder Woman' },
  { draw: 'Captain America' },
  { draw: 'Ant Man' },
  { draw: 'The Joker' },
  { draw: 'The Riddler' },
  { draw: 'Doctor Strange' },
  { draw: 'Millenium Falcon' },
  { draw: 'Death Star' },
  { draw: 'burrito' },
  { draw: 'bacon' },
  { draw: 'taco' },
  { draw: 'scrambled eggs' },
  { draw: 'sausage links' },
  { draw: 'pork roll' },
  { draw: 'goblin' },
  { draw: 'dwarf' },
  { draw: 'hobbit' },
  { draw: 'wizard' },
  { draw: 'knight' },
  { draw: 'excalibur' },
  { draw: 'seashell' },
  { draw: 'snake' },
  { draw: 'eye' },
  { draw: 'slam dunk' },
  { draw: 'torch' },
  { draw: 'jewel' },
  { draw: 'pocket watch' },
  { draw: 'grandfather clock' },
  { draw: 'ace of spades' },
  { draw: 'artist' },
  { draw: 'procrastinate' },
  { draw: 'maternity leave' },
  { draw: 'disorganized' },
  { draw: 'Austin Powers' },
  { draw: 'Dr. Evil' },
  { draw: 'Mr. Rogers' },
  { draw: 'Billy Mays' },
  { draw: 'Bob Ross' },
  { draw: 'pendulum' },
  { draw: 'invitation' },
  { draw: 'jester' },
  { draw: 'manager' },
  { draw: 'applesauce' },
  { draw: 'lunchroom' },
  { draw: 'flag' },
  { draw: 'motorcycle' },
  { draw: 'train' },
  { draw: 'lion' },
  { draw: 'snowman' },
  { draw: 'candy' },
  { draw: 'rabbit' },
  { draw: 'bread' },
  { draw: 'river' },
  { draw: 'finger' },
  { draw: 'baby' },
  { draw: 'carrot' },
  { draw: 'purse' },
  { draw: 'hamburger' },
  { draw: 'king' },
  { draw: 'hotdog' },
  { draw: 'sword' },
  { draw: 'shield' },
  { draw: 'Pikachu' },
  { draw: 'inchworm' },
  { draw: 'tarantula' },
  { draw: 'wheelchair' },
  { draw: 'fist' },
  { draw: 'pea' },
  { draw: 'vase' },
  { draw: 'coast' },
  { draw: 'fax' },
  { draw: 'seed' },
  { draw: 'desert' },
  { draw: 'neighbor' },
  { draw: 'hot dog' },
  { draw: 'tower' },
  { draw: 'zebra' },
  { draw: 'camel' },
  { draw: 'cellphone' },
  { draw: 'laptop' },
  { draw: 'corn' },
  { draw: 'steering wheel' },
  { draw: 'water wheel' },
  { draw: 'saltwater' },
  { draw: 'dragon' },
  { draw: 'pollution' },
  { draw: 'mask' },
  { draw: 'eye patch' },
  { draw: 'peg leg' },
  { draw: 'pirate' },
  { draw: 'parrot' },
  { draw: 'pirate ship' },
  { draw: 'apologize' },
  { draw: 'snowboarding' },
  { draw: 'taxi' },
  { draw: 'screwdriver' },
  { draw: 'monster' },
  { draw: 'room' },
  { draw: 'rowboat' },
  { draw: 'sailboat' },
  { draw: 'mud' },
  { draw: 'curtain' },
  { draw: 'top hat' },
  { draw: 'stomach' },
  { draw: 'magnet' },
  { draw: 'hook' },
  { draw: 'pilot' },
  { draw: 'lantern' },
  { draw: 'corn dog' },
  { draw: 'farm' },
  { draw: 'tractor' },
  { draw: 'bulldozer' },
  { draw: 'rolling pin' },
  { draw: 'oven' },
  { draw: 'microwave' },
  { draw: 'closed' },
  { draw: 'open' },
  { draw: 'railroad' },
  { draw: 'zookeeper' },
  { draw: 'suitcase' },
  { draw: 'squirrel' },
  { draw: 'beaver' },
  { draw: 'light bulb' },
  { draw: 'jacket' },
  { draw: 'sprinkler' },
  { draw: 'fan' },
  { draw: 'chess' },
  { draw: 'cub' },
  { draw: 'rain' },
  { draw: 'globe' },
  { draw: 'park' },
  { draw: 'computer' },
  { draw: 'city' },
  { draw: 'elephant' },
  { draw: 'bag' },
  { draw: 'volcano' },
  { draw: 'tornado' },
  { draw: 'cave' },
  { draw: 'Batmobile' },
  { draw: 'Catwoman' },
  { draw: 'The Penguin' },
  { draw: 'nut' },
  { draw: 'sink' },
  { draw: 'cricket' },
  { draw: 'map' },
  { draw: 'cobra' },
  { draw: 'wreck' },
  { draw: 'nurse' },
  { draw: 'target' },
  { draw: 'flagpole' },
  { draw: 'hot-air balloon' },
  { draw: 'glass' },
  { draw: 'rainstorm' },
  { draw: 'soap' },
  { draw: 'grill' },
  { draw: 'fishing pole' },
  { draw: 'pickaxe' },
  { draw: 'notepad' },
  { draw: 'dollar' },
  { draw: 'pizza' },
  { draw: 'magic carpet' },
  { draw: 'magic lamp' },
  { draw: 'geenie' },
  { draw: 'dad' },
  { draw: 'grandma' },
  { draw: 'mom' },
  { draw: 'helicopter' },
  { draw: 'narwhal' },
  { draw: 'flood' },
  { draw: 'curve' },
  { draw: 'pipe' },
  { draw: 'lip' },
  { draw: 'tub' },
  { draw: 'marry' },
  { draw: 'babysitter' },
  { draw: 'round' },
  { draw: 'violin' },
  { draw: 'guitar' },
  { draw: 'french horn' },
  { draw: 'stain' },
  { draw: 'bat' },
  { draw: 'teapot' },
  { draw: 'cucumber' },
  { draw: 'window' },
  { draw: 'marshmallow' },
  { draw: 'princess' },
  { draw: 'daddy longlegs' },
  { draw: 'laundry basket' },
  { draw: 'hospital' },
  { draw: 'trumpet' },
  { draw: 'drums' },
  { draw: 'magazine' },
  { draw: 'clam' },
  { draw: 'oyster' },
  { draw: 'memory' },
  { draw: 'dugout' },
  { draw: 'quartet' },
  { draw: 'cloak' },
  { draw: 'religion' },
  { draw: 'musician' },
  { draw: 'dust bunny' },
  { draw: 'telephone booth' },
  { draw: 'alarm clock' },
  { draw: 'hairspray' },
  { draw: 'pharmacist' },
  { draw: 'mascot' },
  { draw: 'wag' },
  { draw: 'testify' },
  { draw: 'recess' },
  { draw: 'ski goggles' },
  { draw: 'sunburn' },
  { draw: 'bonnet' },
  { draw: 'parade' },
  { draw: 'marching band' },
  { draw: 'wedding band' },
  { draw: 'swarm' },
  { draw: 'enagement ring' },
  { draw: 'retail' },
  { draw: 'race' },
  { draw: 'vegetarian' },
  { draw: 'barber' },
  { draw: 'taxes' },
  { draw: 'cough' },
  { draw: 'palace' },
  { draw: 'castle' },
  { draw: 'wool' },
  { draw: 'denchers' },
  { draw: 'turtleneck' },
  { draw: 'cushion' },
  { draw: 'freshman' },
  { draw: 'tackle' },
  { draw: 'first class' },
  { draw: 'ceiling fan' },
  { draw: 'raft' },
  { draw: 'fireside' },
  { draw: 'sushi' },
  { draw: 'car dealership' },
  { draw: 'movie' },
  { draw: 'plank' },
  { draw: 'TV antenna' },
  { draw: 'university' },
  { draw: 'humidity' },
  { draw: 'deep' },
  { draw: 'team' },
  { draw: 'football' },
  { draw: 'soccer' },
  { draw: 'baseball' },
  { draw: 'basketball' },
  { draw: 'delivery' },
  { draw: 'pain' },
  { draw: 'ache' },
  { draw: 'scuba diving' },
  { draw: 'snorkeling' },
  { draw: 'sticky note' },
  { draw: 'ping pong' },
  { draw: 'juggle' },
  { draw: 'produce' },
  { draw: 'pigpen' },
  { draw: 'logo' },
  { draw: 'crow\'s nest' },
  { draw: 'bulldog' },
  { draw: 'concession stand' },
  { draw: 'snarl' },
  { draw: 'date' },
  { draw: 'peasant' },
  { draw: 'kneel' },
])

puts 'seeded database'
